# Generated by Django 3.0.3 on 2020-04-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topappliedjobs',
            old_name='job_id',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='topappliedjobs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
