# Generated by Django 3.0.3 on 2020-04-16 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_system_module', '0001_initial'),
        ('recommendation', '0002_auto_20200416_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopAppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_count', models.IntegerField()),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_system_module.Job')),
            ],
        ),
        migrations.DeleteModel(
            name='TopAppliedJobs',
        ),
    ]
