# Generated by Django 3.0.3 on 2020-04-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_system_module', '0002_auto_20200419_1423'),
        ('recommendation', '0003_auto_20200416_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleWhoAppliedThisAlsoApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('also_applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='also_applied_job', to='job_system_module.Job')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job_system_module.Job')),
            ],
        ),
    ]
